### ISSUE TITLE
xcor_gsea() missing parM() function

### ISSUE THREAD

**Issue by SadieVanHorn** [landau-lab/PATH#1]
I've been working on implementing PATH, and have been running into errors with the xcor_gsea function. To troubleshoot, I have worked through the "PATH analysis of glioblastoma" vignette with the data available here, on github, but have found the same error when trying to run xcor_gsea(). The error text is: 

Error in parM(gene.data, weight.matrix) : could not find function "parM"

I cannot find what package this function would belong to, so I'm unsure what could have a version issue or other troubleshooting need.

**Comment by joshseth** [comment]
Hi, thanks for flagging this issue. I've just pushed code for the parM
function, which was not in the repo. Hopefully that solves the problem. If
not, let me know and I'll see what I can do to fix it.

**Comment by SadieVanHorn** [comment]
It's close - one new error with the parM() function: 

Error in select(., Z) : unused argument (Z)

Again, this is just in the vignette, copied directly from github.

**Comment by joshseth** [comment]
I think the select() function call inside xcor_gsea() must've been masked. Specified that it is from the package dplyr now.

**Comment by SadieVanHorn** [comment]
great! It is giving the correct output - Thanks for your help 😃
