### ISSUE TITLE
xcor gives NA when there are 3 clones or nodes in the tree

### ISSUE THREAD

**Issue by Puriney** [landau-lab/PATH#3]
Hello, 

It may not be a coincidence. I applied the PATH on my real data of several samples. All of them successfully got heritability values of `xcor` except two samples that there are 3 nodes/clones in the tree. 

Here, I ran 1000 arbitrary examples they all generate NaN values in the end. 

I was wondering is it expected? 

Many thanks. 
``` R
sapply(1:1000, function(i) {
  cat(i, ' ... ')

  set.seed(42+i)
  
  tree1 <- rtree(n=3)
  # plot(tree1)
  tree1$tip.label
  
  mat_expr <- cbind(heritable=c(1, 40, 40), 
                    plastic = c(40, 1, 40))
  rownames(mat_expr) <- tree1$tip.label
  
  Winv1 <- inv.tree.dist(tree1, node = TRUE, norm = FALSE)
  # signif(Winv1, 2)
  modxcor <- xcor(mat_expr, Winv1)
  Idf <- reshape2::melt(modxcor$Morans.I, 
                        value.name = "I")
  Zdf <- reshape2::melt(modxcor$Z.score, 
                        value.name = "Z")
  
  df <- full_join(Idf, Zdf, by=c("Var1", "Var2"))
  
  df <- df %>% mutate(Var1 = as.factor(Var1), 
                      Var2 = as.factor(Var2))
  
  df <- df %>% filter(Var1 == Var2)
  return( all(is.nan(df$Z)) )
  
}) %>% table()
```
 
 ```
 TRUE 
1000
```

**Comment by joshseth** [comment]
Hi, I think you are seeing NaN z scores because the estimated variance in the `xcor` function is NaN. The variance calculation includes (n-3) terms which will be 0 when the tree only has 3 leaves, as your tree does. You could instead just use a permutation test to generate a z score. The calculation inside the `xcor` function is for a permutation test. 

For example,
``` 
permute_trees <- function(reps, z, w, cores) {
  melt(pbmclapply(1:reps, function(r) xcor(z[sample(1:nrow(z), nrow(z)),], w)$Moran, 
                  mc.cores = cores)) %>% tibble
}

s <- permute_trees(reps = 10^4, z = mat_expr, w = Winv1, cores = 8) %>% 
  group_by(Var1, Var2) %>% summarize("s" = sd(value)) %>% 
  pivot_wider(id_cols = Var1, names_from = Var2, values_from = s) %>% 
  ungroup() %>% column_to_rownames("Var1") %>% as.matrix
  
z  <- (modxcor$Morans.I - modxcor$Expected.I)/s
```

Hope this helps!

**Comment by Puriney** [comment]
Many thanks for your prompt solution! I will test it this week and then close this issue if no more questions/problems. Thanks again.

**Comment by Puriney** [comment]
Great. I confirmed that it works. 

Then processing the `z` and following the same procedure in the tutorial will generate the final values for visualization. 
```
Zdf <- reshape2::melt(z, value.name = 'Z')
```

Many thanks.
