### ISSUE TITLE
How to get phylogenetic correlations between cell state and gene expression across the tree?

### ISSUE THREAD

**Issue by liangzhenhou** [landau-lab/PATH#4]
Hi, Thank for the great tool!
Could you help me how to get the phylogenetic correlations between cell state and gene expression across the tree?
Use **PATH::xcor** ?

**Comment by joshseth** [comment]
Hi, and thanks! 

I think one approach would be to column bind the categorical cell state and gene expression matrices, and then input the combined matrix to `PATH::xcor`. So for example, if you have a (categorical) cell state vector `cell_states` and a gene expression matrix (rows correspond to cells and columns correspond to genes) `G`, first convert the cell state vector into a categorical matrix (with `PATH::catMat`) and then column bind it (with `cbind`) with the gene expression matrix as follows,

`X <- cbind(PATH::catMat(cell_states), G)`. 

Next, compute phylogenetic correlations between all genes and categorical cell states with, 

`M <- PATH::xcor(X, W)`,

 where `W` is your phylogenetic weight matrix. 
 
More generally, you can get phylogenetic correlations between any phenotypes of interest by adding those phenotypes as a column to the matrix you input to the `data` argument for `PATH::xcor`. 

Hope that helps!

**Comment by liangzhenhou** [comment]
Thank you! Very clear answer.
I have the CRISPR-based edits data of single cells. Could you give us an example about how to be input for PATH. Whether PATH require the bifurcated tree? When I run PATH with multifurcated nodes, it raises the error below
<img width="589" alt="1725024723722" src="https://github.com/user-attachments/assets/c1a83037-3f45-46a6-8a56-1d0170400150">

Could you help me solve it? Thank you very much

**Comment by joshseth** [comment]
Hm, I'm not sure what is generating this error. It does not require a bifurcated tree. It might help to look at the cell state frequencies, phylogenetic correlations or state pair frequencies to see if anything is missing. 

For instance, what does `t(catMat(tree$states))%*%one_node_tree_dist(tree)%*%catMat(tree$states)` look like? Can this be row normalized?

**Comment by liangzhenhou** [comment]
> Hm, I'm not sure what is generating this error. It does not require a bifurcated tree. It might help to look at the cell state frequencies, phylogenetic correlations or state pair frequencies to see if anything is missing.
> 
> For instance, what does `t(catMat(tree$states))%*%one_node_tree_dist(tree)%*%catMat(tree$states)` look like? Can this be row normalized?

Thank you for your reply! The result about this process "t(catMat(tree$states))%*%one_node_tree_dist(tree)%*%catMat(tree$states)" is below
![1726128499640](https://github.com/user-attachments/assets/ab321c36-4fcb-4461-a4d0-60b8ff227104)
and then I use this tree to run 'PATH_inf', it will raise the above error "Error in balance(baP$z, "S"): BLAS/LAPACK routine 'DGEBAL' gave error code -3". The tree I used is the CRISPR-based lineage tree with no branch length, could you recommend us the value of the branch length to run PATH_inf ?

**Comment by joshseth** [comment]
The error is probably from missing branch lengths. You could try setting the `PATH_inf(impute_branches = TRUE)`, and supplying an estimate of the sampling, birth and death rates. You could also use an inference that doesn't rely on any branch length estimates, by using the `Pt` output from `PATH_inf()`. Pt is calculated as `PATH:::rowNorm(t(catMat(tree$states))%*%one_node_tree_dist(tree)%*%catMat(tree$states))`.
  
I would also check to make sure that your state-pair matrix sums to 1.
